---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "refund-inbound-processor"
  name: "refund-inbound-processor-deployment"
  namespace: "default"
  ownerReferences: []
spec:
  replicas: 1
  template:
    metadata:
      annotations: {}
      finalizers: []
      labels:
        app: "refund-inbound-processor"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command: []
        env: 
          - name: refund.mb.host
            value: "b7a-mb-service.default.svc.cluster.local"
          - name: refund.mb.port
            value: "5672"
          - name: refund.api.url
            value: "http://refund-data-service-service.default.svc.cluster.local:8280/refund"
        envFrom: []
        image: "rajkumar/refund-inbound-processor:0.1.2"
        imagePullPolicy: "IfNotPresent"
        name: "refund-inbound-processor-deployment"
        ports:        
        volumeMounts: []
      hostAliases: []
      imagePullSecrets: []
      initContainers: []
      nodeSelector: {}
      tolerations: []
      volumes: []
