---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "refund-inbound-processor"
  name: "refund-inbound-processor-deployment"
  namespace: "default"
  ownerReferences: []
spec:
  replicas: 1
  template:
    metadata:
      annotations: {}
      finalizers: []
      labels:
        app: "refund-inbound-processor"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command: []
        env: 
          - name: refund_mb_host
            value: "b7a-mb-service.default.svc.cluster.local"
          - name: refund_mb_port
            value: "5672" 
          - name: ecomm_backend_refund_sftp_host
            value: "refund-sftp-headless-service.default.svc.cluster.local"
          - name: ecomm_backend_refund_sftp_port
            value: "22"    
          - name: ecomm_backend_refund_sftp_username
            value: "ecomm0xxx" 
          - name: ecomm_backend_refund_sftp_password
            value: "ec0mmoxxx" 
          - name: ecomm_backend_refund_sftp_path
            value: "/Users/ecomm0xxx/projects/ecomm/sftp/refund" 
          - name: ecomm_backend_refund_etl_interval
            value: "10000" 
          - name: ecomm_backend_refund_etl_initialDelay
            value: "500"                         
          - name: refund_api_url
            value: "http://refund-data-service-service.default.svc.cluster.local:8280/refund"
        envFrom: []
        image: "rajkumar/refund-inbound-processor:0.1.0"
        imagePullPolicy: "IfNotPresent"
        name: "refund-inbound-processor-deployment"
        ports:        
        volumeMounts: []
      hostAliases: []
      imagePullSecrets: []
      initContainers: []
      nodeSelector: {}
      tolerations: []
      volumes: []
