---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "refund-data-service"
    integration: "refund"
  name: "refund-data-service-deployment"
  namespace: "default"
  ownerReferences: []
spec:
  replicas: 1
  template:
    metadata:
      annotations: {}
      finalizers: []
      labels:
        app: "refund-data-service"
        integration: "refund"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command: []
        env:        
          - name: refund_db_host
            value: "staging-db-headless-service.default.svc.cluster.local"
          - name: refund_db_port
            value: "3306"    
          - name: refund_db_name
            value: "WSO2_STAGING" 
          - name: refund_db_username
            valueFrom:
              secretKeyRef:
                name: staging-db-secret
                key: username  
          - name: refund_db_password
            valueFrom:
              secretKeyRef:
                name: staging-db-secret
                key: password 
        envFrom: []
        image: "rajkumar/refund-data-service:0.1.0"
        imagePullPolicy: "Always"
        name: "refund-data-service-deployment"
        ports:       
        - containerPort: 8280
          name: http         
        volumeMounts: []
      hostAliases: []
      imagePullSecrets: []
      initContainers: []
      nodeSelector: {}
      tolerations: []
      volumes: []
